### ISSUE TITLE
FHIR 3.0.0 (STU3) is not supported

### ISSUE THREAD

**Issue by phibn** [cqframework/cql-exec-fhir#1]
Hi @cmoesel, 
I am a big fan of NodeJS. Do you plan to release the library that supports FHIR 3.0.0 (STU3)?

**Comment by cmoesel** [comment]
I expect we will eventually need it, and at that point, we will develop it and release it.  But...  I don't know when that will be.  There is not yet a specific date for it.

We'd be glad to take a contribution in the form of a pull request if you decide to work on it yourself.  If you look at the current code, you can see that it is mainly based on dynamically reading in "modelinfo" files.  Adding support for STU3 would likely require only a few changes:

- Add the model info file for FHIR 3.0.0 (found [here](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/quick/src/main/resources/org/hl7/fhir/fhir-modelinfo-3.0.0.xml)) (should be easy)
- Add support for the new ChoiceTypeSpecifier construct which was introduced in the FHIR 3.0.0 modelinfo (a bit more complexity)

**Comment by cmoesel** [comment]
Hi @kugoo109 - I just wanted to let you know that FHIR 3.0.0 (STU3) support has been added in release 1.1.0.  I'll be closing this issue now, but let me know if you have any questions.
