### ISSUE TITLE
FHIR R4 Support

### ISSUE THREAD

**Issue by jawalonoski** [cqframework/cql-exec-fhir#5]
Are there plans to support FHIR R4?

If so, is there a timeline?

**Comment by cmoesel** [comment]
Hi @jawalonoski -- I haven't yet confirmed, but I'm hoping we can add R4 in the next 1-2 months.  I'll keep you posted.

**Comment by cmoesel** [comment]
FHIR R4 support has just been added in version 1.3.0.  Thanks for the suggestion and support.

https://github.com/cqframework/cql-exec-fhir/releases/tag/v1.3.0
